### ISSUE TITLE
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by mflisikowski** [peterdotjs/atom-synced-sidebar#11]
Atom v.1.0.13

Information: Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

Log:
gyp ERR! build error 
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Users\mflisikowski\AppData\Local\atom\app-1.0.13\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\Users\mflisikowski\AppData\Local\atom\app-1.0.13\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Users\mflisikowski.atom\packages\synced-sidebar\node_modules\pathwatcher
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\Users\mflisikowski\AppData\Local\atom\app-1.0.13\resources\app\apm\bin\node.exe" "D:\Users\mflisikowski\AppData\Local\atom\app-1.0.13\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "D:\Users\mflisikowski\.atom\.apm\.apmrc" "--userconfig" "D:\Users\mflisikowski\.atom\.apmrc" "rebuild" "--target=0.30.6" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! pathwatcher@3.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher@3.3.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pathwatcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pathwatcher
npm ERR! There is likely additional logging output above.

**Comment by amebel** [comment]
same here but on Ubuntu 15.04

**Comment by n1k0sv** [comment]
Happens on OSX as well, so I guess its a global issue across all platforms.

**Comment by zenopopovici** [comment]
Can be closed, it's an Atom bug: https://github.com/atom/atom/issues/8837

**Comment by peterdotjs** [comment]
Thanks a lot @zenopopovici  for the info.

@MateuszFlisikowski @AmeBel @nbasili  you guys can try the workaround listed in https://github.com/atom/atom/issues/8837

**Comment by n1k0sv** [comment]
@peterdotjs Works fine on the latest atom 1.0.15, so I guess we are good to go. Congrats btw on the plugin, its amazingly useful.

**Comment by rugk** [comment]
Even  with Atom 1.0.15 I'm still getting this issue:

```
Installing package synced-sidebar failed Error: Installing “synced-sidebar@undefined” failed.
  at C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:384:21
  at exit (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

> runas@2.0.0 install D:\Users\%username%\AppData\Local\Temp\apm-install-dir-115821-4416-1cvt2c6\node_modules\synced-sidebar\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild


D:\Users\%username%\AppData\Local\Temp\apm-install-dir-115821-4416-1cvt2c6\node_modules\synced-sidebar\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\%username%\\AppData\\Local\\atom\\app-1.0.15\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\%username%\\AppData\\Local\\atom\\app-1.0.15\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "D:\\Users\\%username%\\.atom\\.apm\\.apmrc" "--userconfig" "D:\\Users\\%username%\\.atom\\.apmrc" "install" "D:\\Users\\%username%\\AppData\\Local\\Temp\\d-115821-4416-1yaxd2t\\package.tgz" "--target=0.30.6" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.


(anonymous function) @ C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-card.js:641
C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\pac…:641 Installing package synced-sidebar failed Error: Installing “synced-sidebar@undefined” failed.
  at C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:384:21
  at exit (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

> runas@2.0.0 install D:\Users\%username%\AppData\Local\Temp\apm-install-dir-115821-7460-1pi0mga\node_modules\synced-sidebar\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild


D:\Users\%username%\AppData\Local\Temp\apm-install-dir-115821-7460-1pi0mga\node_modules\synced-sidebar\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\%username%\\AppData\\Local\\atom\\app-1.0.15\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\%username%\\AppData\\Local\\atom\\app-1.0.15\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "D:\\Users\\%username%\\.atom\\.apm\\.apmrc" "--userconfig" "D:\\Users\\%username%\\.atom\\.apmrc" "install" "D:\\Users\\%username%\\AppData\\Local\\Temp\\d-115821-7460-100ekds\\package.tgz" "--target=0.30.6" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
```

**Comment by DannyDannyDanny** [comment]
Search _Incompatible Packages: View_ in the command palette with `ctrl + shift + p`.
Run **Reload Packages** :man_shrugging:

 **OS:** Windows 7 Enterprise (6.1)
